createOrReplace

	ref table Customer

		measure '# Customers' = COUNTROWS('Customer')
			formatString: #,##0
			lineageTag: a8dc565a-aa9b-40dc-902c-1ba2596b0977

	ref table Product

		measure '# Products' = COUNTROWS('Product')
			formatString: #,##0
			lineageTag: 1f8f1a2a-06b6-4989-8af7-212719cf3617

	ref table Sales

		measure '# Customers (w/ Sales)' = DISTINCTCOUNT('Sales'[CustomerKey])
			formatString: #,##0
			lineageTag: 4ec872f0-a42d-4aa9-bf6b-1ca7c4916336

		measure '# Sales' = COUNTROWS('Sales')
			formatString: #,##02
			lineageTag: 67791bd1-5f33-4a29-a9ac-be0ad2453fcf

		measure Cost =
				SUMX(
					Sales,
					Sales[Quantity] * Sales[Unit Cost]
				)
			formatString: $ #,##0
			lineageTag: 3e5cb67e-a411-476f-ad34-7ec10dfd084d

		measure Margin =
				SUMX(
					Sales,
					Sales[Quantity]
					* (Sales[Net Price] - Sales[Unit Cost])
				)
			formatString: $ #,##0
			lineageTag: d22a262b-b776-4ccd-b9bd-7ef9c90eba51

		measure 'Sales Amount' =
				SUMX(
					'Sales',
					'Sales'[Quantity] * 'Sales'[Net Price]
				)
			formatString: $ #,##0
			lineageTag: a8e95485-02a2-4525-b02a-b2418fbdbe4c

		measure 'Sales Amount (12M average)' =
				VAR v_selDate =
				MAX('Calendar'[Date])
				VAR v_period =
				DATESINPERIOD(
					'Calendar'[Date],
					v_selDate,
					-12,
					MONTH
				)
				VAR v_result =
				CALCULATE(
					AVERAGEX(
						VALUES('Calendar'[Date]),
						[Sales Amount]
					),
					v_period
				)
				VAR v_firstDate =
				MINX(
					v_period,
					'Calendar'[Date]
				)
				VAR v_lastDateSales =
				MAX(Sales[Order Date])
				RETURN
					IF(
						v_firstDate <= v_lastDateSales,
						v_result
					)
			formatString: $ #,##0
			lineageTag: 7fd60f7e-287e-46c3-a745-24c4507bc77b

		measure 'Sales Amount (6M average)' =
				VAR v_selDate =
				MAX('Calendar'[Date])
				VAR v_period =
				DATESINPERIOD(
					'Calendar'[Date],
					v_selDate,
					-6,
					MONTH
				)
				VAR v_result =
				CALCULATE(
					AVERAGEX(
						VALUES('Calendar'[Date]),
						[Sales Amount]
					),
					v_period
				)
				VAR v_firstDate =
				MINX(
					v_period,
					'Calendar'[Date]
				)
				VAR v_lastDateSales =
				MAX(Sales[Order Date])
				RETURN
					IF(
						v_firstDate <= v_lastDateSales,
						v_result
					)
			formatString: $ #,##0
			lineageTag: 9a48bea0-e5fb-40fa-9e81-f61288e31a02

		measure 'Sales Amount (LY)' =
				IF(
					[Sales Amount] > 0,
					CALCULATE(
						[Sales Amount],
						SAMEPERIODLASTYEAR('Calendar'[Date])
					)
				)
			formatString: "$"#,0.###############;("$"#,0.###############);"$"#,0.###############
			lineageTag: 3fa889ae-64b9-4a6e-b0e6-c81c90fd32bf

		measure 'Sales Amount Avg per Day' =
				AVERAGEX(
					VALUES('Calendar'[Date]),
					[Sales Amount]
				)
			formatString: $ #,##0
			lineageTag: 65842ce7-7176-4106-868e-2e83aaa62b4c

		measure 'Sales Qty' = SUM('Sales'[Quantity])
			formatString: #,##0
			displayFolder: Qty
			lineageTag: c2ff8d96-2f03-4005-84df-91458625b73b

		measure 'Sales Qty (LY)' = IF ([Sales Qty] > 0, CALCULATE([Sales Qty], SAMEPERIODLASTYEAR('Calendar'[Date])))
			formatString: #,##0
			displayFolder: Qty
			lineageTag: 019cfc4f-2a3e-707b-bbcd-5c25d64f9ae3

		measure 'Sales Qty Avg per Day' = AVERAGEX(VALUES('Calendar'[Date]), [Sales Qty])
			formatString: #,##0
			displayFolder: Qty
			lineageTag: 019cfc4f-389b-746b-b1fc-10efd87530bf

	ref table Store

		measure '# Stores' = COUNTROWS('Store')
			formatString: #,##0
			lineageTag: 868df9c8-f579-47d1-a776-3d29121df7c7

